name: Update Quant Dashboard
on:
  schedule:
    # Esegue lo script alle 23:00 UTC (dopo la chiusura di Wall Street) dal Lun al Ven
    - cron: '0 23 * * 1-5'
  workflow_dispatch: # Questo abilita il pulsante per l'avvio manuale

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Esegui lo script
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python main.py
